const faker = require("faker");
const uuidv4 = require("uuid/v4");

//alter these values to generate different amounts of faked, seeded data
const userSeeds = 501;
const seriesSeeds = 20;
const memberSeeds = 500; // 500 fake users will be generated by Faker.js
const messageSeeds = 20;

module.exports = {
  createFakeUsers,
  createFakeTrainingSeries,
  createFakeMessages,
  createFakeClasses
};

function createFakeUsers() {
  const newUsers = [];
  const fakeUser = () => ({
    first_name: faker.name.firstName(),
    last_name: faker.name.lastName(),
    email: faker.internet.email(),
    role: "volunteer"
  });
  for (let i = 0; i < userSeeds; i++) {
    newUsers.push(fakeUser());
  }
  return newUsers;
}

function createFakeTrainingSeries() {
  const newSeries = [];
  const fakeSeries = () => ({
    title: faker.company.catchPhrase(),
    user_id: faker.random.number({
      min: 1,
      max: userSeeds
    })
  });

  for (let i = 0; i < seriesSeeds; i++) {
    newSeries.push(fakeSeries());
  }

  return newSeries;
}

function createFakeMessages() {
  const newMessages = [];
  const fakeMessage = () => ({
    subject: faker.company.catchPhrase(),
    body: faker.company.bs(),
    link: faker.internet.url(),
    training_series_id: faker.random.number({
      min: 1,
      max: seriesSeeds
    })
  });
  for (let i = 0; i < messageSeeds; i++) {
    newMessages.push(fakeMessage());
  }
  return newMessages;
}

function createFakeClasses() {
  const newClasses = [];
  const fakeClasses = () => ({
    class_name: faker.name.firstName(),
    grade_level: faker.random.number({ min: 1, max: 11 }),
    subject: faker.commerce.department(),
    number_of_students: faker.random.number({ min: 1, max: 5 }),
    volunteer_id: faker.random.number({ min: 1, max: 50 })
  });
  for (let i = 0; i < userSeeds; i++) {
    newClasses.push(fakeClasses());
  }

  return newClasses;
}
